name: prizepots
description: An Application to earn money and support charity organisations

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  admob_flutter: ^0.3.1
  ads: ^1.7.2
  http: ^0.12.0
  shared_preferences: ^0.5.6
  random_string: ^2.0.1
  fluttertoast: ^3.1.3
  url_launcher: ^5.4.1
  animator: ^1.0.0
  pie_chart: ^3.1.1
  fl_chart: ^0.8.1
  flutter_swiper: ^1.1.6
  firebase_core: ^0.4.0
#  firebase_auth: ^0.11.1+6
#  cloud_firestore: ^0.12.5
  firebase_messaging: ^5.1.2
  timezone: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
    android: true
    ios: true
    image_path: "assets/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  fonts:
    - family: ColaborateThin
      fonts:
        - asset: fonts/ColabThi.otf
    - family: Beauty
      fonts:
        - asset: fonts/Beauty.otf
    - family: TextMe
      fonts:
        - asset: fonts/TextMeOne.otf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
